"""empty message

Revision ID: 600bf3b15352
Revises: 448edbb0cbb0
Create Date: 2025-05-09 11:48:33.753115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '600bf3b15352'
down_revision = '448edbb0cbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index('hospital_id')
        batch_op.drop_index('name')
        batch_op.create_unique_constraint('uix_hospital_department', ['hospital_id', 'name'])

    with op.batch_alter_table('doctor_info', schema=None) as batch_op:
        batch_op.alter_column('internal_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=8),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_foreign_key(None, 'doctor', ['id'], ['id'])

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('departments')

    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=11),
               comment=None,
               existing_comment='手机号码',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='姓名',
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('male', 'femal', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Enum('male', 'female'),
               comment=None,
               existing_comment='性别',
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='家庭地址',
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='头像',
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='出生日期',
               existing_nullable=True)
        batch_op.alter_column('medical_history',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='既往病史',
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_foreign_key(None, 'patient', ['id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('medical_history',
               existing_type=mysql.TEXT(),
               comment='既往病史',
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               comment='出生日期',
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='头像',
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               comment='家庭地址',
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('male', 'female'),
               type_=mysql.ENUM('male', 'femal', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='性别',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment='姓名',
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=11),
               comment='手机号码',
               existing_nullable=False)

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departments', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('doctor_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('internal_id',
               existing_type=sa.String(length=8),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=8),
               existing_nullable=True)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint('uix_hospital_department', type_='unique')
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('hospital_id', ['hospital_id'], unique=True)

    # ### end Alembic commands ###
